name: Web build workflow

on:
  workflow_run:
    workflows: Test workflow
    branches: main
    types: completed

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.commit_secret}}
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
    - name: Install dependencies
      run: flutter packages get
    - name: Build web
      run: flutter build web --release --base-href "/clean-arch-formation/"
    - name: Publish
      run: |
        cd build/web
        git init
        git config --global user.email rouxguillaume8@gmail.com 
        git config --global user.name "Guillaume Roux"
        git remote add origin https://${{secrets.commit_secret}}@github.com/TesteurManiak/clean-arch-formation.git
        git checkout -b gh-pages
        git add --all
        git commit -m "update"
        git push origin gh-pages -f